services:
  - type: web
    name: music-vault-starter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: REPLICATE_API_TOKEN
        value: your_replicate_api_token